# Grid parameters
x_wall = 0.5e-3
x_bulk = 10e-3
r = 1.05

# Turbulence parameters
RASModel = "v2f"
bSource = false
highRe = false
THFM = "GGDH"

# Simulation parameters
LTS = true
maxCo = 0.20
decompMethod = "simple"
nDecomp = "(2 1 2)"
n_processors = 4

